---
baseURL: https://ahmedoyeleke.com
languageCode: en-us
title: Ahmed Oyeleke
theme: Ahmed-Oyeleke
paginate: "9"
copyright: 
googleAnalytics: G-1K4E6L1DC5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Ahmed Oyeleke
  description: Personal website for Ahmed Oyeleke, Expert Data/Business Analyst and Agile Project Manager
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: Ahmed Oyeleke
    text: Ahmed Oyeleke
    lightNavIcon: /uploads/sun.svg
    darkNavIcon: /uploads/zap.svg
    iconHeight: "35"
    iconWIdth: "35"
  comments: true
  mainSections:
  - portfolio
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: https://fabform.io/f/6MFfZ8s
  assets:
    disableFingerprinting: false
    favicon: /uploads/zap.svg
    favicon16x16: /uploads/zap.svg
    favicon32x32: /uploads/zap.svg
    apple_touch_icon: /uploads/zap.svg
    safari_pinned_tab: /uploads/zap.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Ahmed Oyeleke
    heroDescription: Expert Data/Business Analyst and Agile Project Manager
    heroCTAPrimaryText: Portfolio
    heroCTAPrimaryUrl: "/portfolio/"
    heroCTASecondaryText: Connect on LinkedIn
    heroCTASecondaryUrl: https://www.linkedin.com/in/ahmed-oyeleke/\
    heroCTATetText: Download Resume
    heroCTATetUrl: "/uploads/ahmedoyelekecv.pdf"
    heroBackgroundImage: "/uploads/portfolio-1.webp"
    
    # About Section    
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: A brief introduction
    aboutImgUrl: "/uploads/ahmedphoto.jpg"
    
    
    # Blog Section, Actually Portfolio but we didnt want to rename
    disableBlogSection: false
    blogTitle: Portfolio Snippets
    blogDescription: Click on a snippet to see more
    seeMoreText: View More
    
    
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Portfolio
    title: Portfolio
    pre: pen-tool
    url: "/portfolio"
    weight: "20"
  
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  

  # Everything below is orphaned since we removed search
  search: # Search page's quick links
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
